# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0101f902a2e0cdd4e034a74d93b4fd60fb23d81cfb236c7c2bc3ac133f2af39fc809770094a6dab1230cbaae8763e71c4e75e4ebef69a5cb3c9641df2ed15ea3

test:
  secret_key_base: 2d3f30dc5627a4d5a8146521e81545698f0f904c67a1b43cdf3d2bed4587f62726ae29d04d0bc50a80866f8672d220bd54387322359be63659f8c69819966462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
